<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>innerDevice</name>
   <tag></tag>
   <elementGuidId>cd0b23e0-1a05-4166-856f-80e11789e07b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[count(. | //*[@id = 'select2-7064-zn-container']) = count(//*[@id = 'select2-7064-zn-container'])][count(. | //*[@title = '-Ничего-не-выбрано-']) = count(//*[@title = '-Ничего-не-выбрано-'])][count(. | //*[text() = '-Ничего-не-выбрано-']) = count(//*[text() = '-Ничего-не-выбрано-'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//select[@name= '7064']/../span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-7064-zn-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-Ничего-не-выбрано-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Ничего-не-выбрано-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-7064-zn-container&quot;)</value>
   </webElementProperties>
</WebElementEntity>
