<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DefectPage</name>
   <tag></tag>
   <elementGuidId>e495aae6-bb7e-494f-935b-dd38ae4f3bbc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ancestorgroupid</name>
      <type>Main</type>
      <value>501</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preview</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>groupid</name>
      <type>Main</type>
      <value>501</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm ui-tab-modal  m-m-el-btn-ui-tab</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Выявленные дефекты</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m-m-i4618447&quot;)/div[@class=&quot;jsPanel-content&quot;]/div[@class=&quot;m-m-el-gr-cloth&quot;]/div[@class=&quot;ui-modal-tab-container m-m-tab-container&quot;]/div[@id=&quot;ui-container-tab&quot;]/button[@class=&quot;btn btn-default btn-sm ui-tab-modal  m-m-el-btn-ui-tab&quot;]</value>
   </webElementProperties>
</WebElementEntity>
