<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ABT-4</name>
   <tag></tag>
   <elementGuidId>a07ef105-2848-41bf-a08e-1a626b0e2c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//ul[@class= 'select2-results__options']/li[text()='АВТ-4']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[count(. | //*[@id = 'select2-6327-0t-result-k02z-28692']) = count(//*[@id = 'select2-6327-0t-result-k02z-28692'])][count(. | //*[text() = 'АВТ-4']) = count(//*[text() = 'АВТ-4'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-6327-0t-result-k02z-28692</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>АВТ-4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@class=&quot;select2-container select2-container--bootstrap select2-container--open&quot;]/span[@class=&quot;select2-dropdown select2-dropdown--below&quot;]/span[@class=&quot;select2-results&quot;]/ul[@id=&quot;select2-6327-0t-results&quot;]/li[@id=&quot;select2-6327-0t-result-k02z-28692&quot;]</value>
   </webElementProperties>
</WebElementEntity>
