<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_test101010</name>
   <tag></tag>
   <elementGuidId>d6aa08b1-c1df-4ef8-a304-ef803830eeb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[text() = 'test1010'][count(. | id(&quot;admin_editable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]) = count(id(&quot;admin_editable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;admin_editable&quot;]/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test1010</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin_editable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
