<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StructureButton</name>
   <tag></tag>
   <elementGuidId>843c02e5-9725-4b5d-b516-15b555257702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[count(. | //*[@type = 'button']) = count(//*[@type = 'button'])][count(. | //*[text() = 'Структура предприятия АО КНПЗ']) = count(//*[text() = 'Структура предприятия АО КНПЗ'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//*[text()=&quot;Структура предприятия АО КНПЗ&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeid</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>groupid</name>
      <type>Main</type>
      <value>1209</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isdiagram</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modalname</name>
      <type>Main</type>
      <value>[6316]/[6312]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm ui-tab  m-t-el-btn-ui-tab</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>horizontal</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Структура предприятия АО КНПЗ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-flexcroll&quot;)/div[@id=&quot;ui-container-tab&quot;]/button[@class=&quot;btn btn-default btn-sm ui-tab  m-t-el-btn-ui-tab&quot;]</value>
   </webElementProperties>
</WebElementEntity>
