<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CalculationButton</name>
   <tag></tag>
   <elementGuidId>f77cf69e-4996-43fc-9ce9-c26c9bdf6ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@objtypeid = '1072']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>calcparamid</name>
      <type>Main</type>
      <value>[{&quot;Name&quot;:&quot;Добавить&quot;,&quot;DefBut&quot;:2,&quot;AllTabs&quot;:1,&quot;Tabs&quot;:[],&quot;ID&quot;:&quot;-1&quot;},{&quot;Name&quot;:&quot;Сохранить&quot;,&quot;DefBut&quot;:1,&quot;AllTabs&quot;:1,&quot;Tabs&quot;:[],&quot;ID&quot;:&quot;-1&quot;},{&quot;Name&quot;:&quot;Создать все элементы ТУ&quot;,&quot;DefBut&quot;:0,&quot;AllTabs&quot;:1,&quot;Tabs&quot;:[],&quot;ID&quot;:&quot;7427&quot;}]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parentinterfaceid</name>
      <type>Main</type>
      <value>2737</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#m-m-ac-105089</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>load</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>istablevisible</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkonlydirectparrent</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>interfaceid</name>
      <type>Main</type>
      <value>2761</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objtypeid</name>
      <type>Main</type>
      <value>1072</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm ui-tab-modal active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Расчеты прочностные</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmitForm&quot;)/div[@class=&quot;form-inline ui-modal-grid-1 split split-horizontal&quot;]/div[@class=&quot;m-m_el_co_cloth&quot;]/div[@class=&quot;m-m-el-cloth-param&quot;]/div[@class=&quot;ui-container-tab m-m-el-table-tab-co&quot;]/button[@class=&quot;btn btn-default btn-sm ui-tab-modal active&quot;]</value>
   </webElementProperties>
</WebElementEntity>
