<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateCalculation</name>
   <tag></tag>
   <elementGuidId>e81c0b7f-cf43-4cbd-95fd-2aa9d805806d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>7338</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control isName </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Введите дату</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m-m-i748063-ADD&quot;)/div[@class=&quot;jsPanel-content&quot;]/form[@id=&quot;SubmitForm&quot;]/div[@class=&quot;form-inline ui-modal-grid-1 split split-horizontal&quot;]/div[@class=&quot;m-m_el_co_cloth&quot;]/div[@class=&quot;m-m-el-cloth-param&quot;]/div[@class=&quot;form-group input-large&quot;]/div[@class=&quot;input-group date&quot;]/input[@class=&quot;form-control isName&quot;]</value>
   </webElementProperties>
</WebElementEntity>
