<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectSourceEnviroment</name>
   <tag></tag>
   <elementGuidId>b48faae4-abf3-4ee4-9e85-2c0b2cef51f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//ul[@class= 'select2-results__options']/li[text()='ЭПБ']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[count(. | //*[@id = 'select2-7253-j3-container']) = count(//*[@id = 'select2-7253-j3-container'])][count(. | //*[@title = '-Ничего-не-выбрано-']) = count(//*[@title = '-Ничего-не-выбрано-'])][count(. | //*[text() = '-Ничего-не-выбрано-']) = count(//*[text() = '-Ничего-не-выбрано-'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-7253-j3-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-Ничего-не-выбрано-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Ничего-не-выбрано-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-7253-j3-container&quot;)</value>
   </webElementProperties>
</WebElementEntity>
